language: node_js

node_js:
  - "10"

cache: npm

before_script:
  - npm install

script:
  # run unit tests
  - npm run test:ci
  # update Protractor and Selenium including ChromeDriver
  - npm run webdriver-update
  # launch Selenium standalone in the background
  #- npm run webdriver-start
  # run Protractor E2E tests
  #- npm run e2e:ci

after_success:
  - npm run typedoc
