language: node_js
node_js:
  - "5"
  - "5.1"
dist: trusty
before_script:
  # For Firefox support.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  apt:
    sources:
      # add PPAs with more up-to-date toolchains
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      # install toolchains
      - gcc-5
      - g++-5
      - clang-3.6
