version: "3"
services:
  web:
    image: node:10
    container_name: "oy-web"
    links:
      - couchdb
    ports:
      - "8081:8081"
    volumes:
      - ./www:/usr/src/app
  couchdb:
    image: couchdb
    container_name: "oy-db"
    ports:
      - "5984:5984"
