version: "3"
services:
  web:
    build: .
    container_name: "oy-web"
    ports:
      - "3000:3000"
    volumes:
      - ./www:/usr/src/app
    command: node server.js
  e2e:
    build: .
    container_name: "oy-e2e"
    links:
      - web
    ports:
      - 4000:4000
    command: npm run e2e
