import { Subject } from "rxjs";
import { Injectable } from "injection-js";

@Injectable()
export class ClientActions {
  // low level actions
  public connectAction = new Subject<any>();
  public disconnectAction = new Subject<any>();
  public joinAction = new Subject<any>();
  // send a chat event in the lobby or level
  public chatAction = new Subject<any>();

  // set position and velocity info generated by a client to dispatch to others
  public syncAction = new Subject<any>();
}

export enum ClientActionTypes {
  Connect = "[Client] Connect action",
  Disconnect = "[Client] Disconnect action",
  Chat = "[Client] Chat action",
  Move = "[Client] Move",
}
export interface Action {
  type: ClientActionTypes;
  payload?: any;
}
